src/PUGX/BookBundle/Form/Type/BookType.php
<?php

namespace PUGX\BookBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title')
            ->add('author')
            ->add('publicationDate', null, array(
                'widget' => 'single_text',
                'format' => 'dd-MM-yyyy',
            ))
            ->add('submit', 'submit')
        ;
    }

    public function getName()
    {
        return 'book';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'PUGX\BookBundle\Entity\Book',
        ));
    }

}

src/PUGX/BookBundle/Controller/DefaultController.php
<?php

namespace PUGX\BookBundle\Controller;

use PUGX\BookBundle\Event\BookCreationEvent;
use Symfony\Component\HttpFoundation\Request;
use PUGX\BookBundle\Entity\Book;
use PUGX\BookBundle\Form\Type\BookType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function indexAction()
    {
        return $this->render('PUGXBookBundle:Default:index.html.twig');
    }

    public function booksAction()
    {
        $em    = $this->getDoctrine()->getManager();
        $books = $em->getRepository('PUGXBookBundle:Book')->findAllWithAuthors();

        return $this->render('PUGXBookBundle:Default:books.html.twig', array('books' => $books));
    }

    public function bookDetailAction($bookId)
    {
        $em   = $this->getDoctrine()->getManager();
        $book = $em->getRepository('PUGXBookBundle:Book')->findOneById($bookId);

        if (!$book) {
            throw $this->createNotFoundException('Book not found');
        }

        return $this->render('PUGXBookBundle:Default:bookDetail.html.twig', array('book' => $book));
    }

    public function bookCreateAction(Request $request)
    {
        $book = new Book();

        $form = $this->createForm(new BookType(), $book);

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($book);
                $em->flush();

                //$this->get('pugx_book.mailer')->sendNewBookNotification($book);
                $dispatcher = $this->container->get('event_dispatcher');
                $event      = new BookCreationEvent($book);

                $dispatcher->dispatch('pugx.book-creation', $event);

                $this->get('session')->getFlashBag()->add('notice', 'Book successfully created');

                return $this->redirect($this->generateUrl('pugx_book_list'));
            }
        }

        return $this->render('PUGXBookBundle:Default:bookCreate.html.twig', array('form' => $form->createView()));
    }

    public function bookDeleteAction($bookId)
    {
        $em   = $this->getDoctrine()->getManager();
        $book = $em->getRepository('PUGXBookBundle:Book')->findOneById($bookId);

        if (!$book) {
            throw $this->createNotFoundException('Book not found');
        }

        $em->remove($book);
        $em->flush();

        $this->get('session')->getFlashBag()->add('notice', 'Book successfully deleted');

        return $this->redirect($this->generateUrl('pugx_book_list'));
    }

}

src/PUGX/BookBundle/Resources/views/Default/bookCreate.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    <h1>Create Book</h1>

    {{ form(form) }}
{% endblock %}

src/PUGX/BookBundle/Resources/views/Default/bookDetail.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    <article id="book-detail">
        <h1>{{ book.title }}</h1> by {{ book.author.name }} {{ book.author.surname }}
        <p>
            Published: {{ book.publicationDate|date("d/m/Y") }}
        </p>
    </article>
{% endblock %}

src/PUGX/BookBundle/Resources/views/Default/books.html.twig
{% extends '::base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}

    <link href="{{ asset('bundles/pugxbook/css/table.css') }}" type="text/css" rel="stylesheet" />
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/pugxbook/js/table.js') }}" type="text/javascript"></script>
{% endblock %}

{% block content %}
    <h1>Book list</h1>

    {% for flashMessage in app.session.flashbag.get('notice') %}
        <div class="notice">
            {{ flashMessage }}
        </div>
    {% endfor %}

    <table class="book-list">
        <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Publication Date</th>
        </tr>
        </thead>
        <tbody>
        {% for book in books %}
            <tr class="{{ cycle(['odd', 'even'], loop.index) }}">
                <td><a href="{{ path('pugx_book_detail', {'bookId':book.id}) }}">{{ book.title }}</a></td>
                <td>{{ book.author.name }} {{ book.author.surname }}</td>
                <td>{{ book.publicationDate | date('d-m-Y') }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/PUGX/BookBundle/Resources/views/Default/index.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    <h1>Welcome on PUGX Book</h1>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultrices, nisi quis porta fermentum, magna ligula suscipit metus, quis blandit leo urna non diam. Sed non dui dui, quis porttitor massa. Phasellus convallis porta leo, sed vehicula eros ultrices sit amet. </p>
{% endblock %}